version: "3.3"
services:
  film_review_service:
    container_name: film_review_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - './.env'
